pkg/blockerslack/reporters/blockers: Fix unit test compilation
Avoid:

  $ go test ./pkg/blockerslack/reporters/blockers
  # github.com/openshift/bugzilla-tools/pkg/blockerslack/reporters/blockers [github.com/openshift/bugzilla-tools/pkg/blockerslack/reporters/blockers.test]
  pkg/blockerslack/reporters/blockers/blockers_test.go:113:23: not enough arguments in call to triageBug
  																														 have (string, []bugzilla.Bug...)
  																														 want (string, string, ...*bugzilla.Bug)
  pkg/blockerslack/reporters/blockers/blockers_test.go:118:74: cannot use *bug (type bugzilla.Bug) as type *bugzilla.Bug in argument to bugutil.FormatBugMessage
  pkg/blockerslack/reporters/blockers/blockers_test.go:124:70: cannot use *bug (type bugzilla.Bug) as type *bugzilla.Bug in argument to bugutil.FormatBugMessage
  FAIL																												 github.com/openshift/bugzilla-tools/pkg/blockerslack/reporters/blockers [build failed]
  FAIL

Not sure if these ever passed, because triageBug was born with the
'who' argument and FormatBugMessage was born with a *Bug argument in
in 3f31f542cc (New command to send team and personl slack messages
about bug status, 2020-07-02).