pkg/blockerslack/reporters/blockers: Use 4.6.z as higher than 4.6.0
Avoid:

  $ go test ./pkg/blockerslack/reporters/blockers
  --- FAIL: TestNewBlockersReporter_Triage (0.00s)
      --- FAIL: TestNewBlockersReporter_Triage/bug_target_release_is_higher_than_target (0.00s)
          blockers_test.go:128: expected:

               as blockers, got:
              > <https://bugzilla.redhat.com/show_bug.cgi?id=1|#1> [**]
  FAIL
  FAIL		github.com/openshift/bugzilla-tools/pkg/blockerslack/reporters/blockers	0.010s
  FAIL

Fixing a bug from 3f31f542cc (New command to send team and personl
slack messages about bug status, 2020-07-02), which was expecting a
4.6.0 bug to not count as a 4.6.0 blocker.